## This file contains project build configuration

name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files
        run: ls -la

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 19
          distribution: 'adopt'

      - name: Change directory and run command
        working-directory: ./finzo
        run: |
          chmod +x ./gradlew
          ./gradlew build


